### ISSUE TITLE
TODO (Сделать до 10.10)

### ISSUE THREAD

**Issue by Barkosss** [Barkosss/Permanager#25]
- [x] Работу с JSON файлом вынести в отдельный метод ([#15](https://github.com/Barkosss/Permanager/pull/15#discussion_r1788915593), [#15](https://github.com/Barkosss/Permanager/pull/15#discussion_r1788917450))
    - [x] Добавить ко всем командам результат у `getCommandName()` и `getCommandDescription()`
- [ ] Валидация: Реализовать через `Optional<Integer/LocalDate>` (Ответственный @ci7iZ4n)
- [x] Подумать над названием пакета, с `constructors` на `models`
- [x] Подумать над [названием поля](https://github.com/Barkosss/Permanager/pull/15#discussion_r1788930469)
- [x] ~~Изменить типы данных на `enum` в местах с небольшими диапозонами~~ (Было переделано под отдельный класс с использование `int`)
- [ ] Добавить комментарии в коде
