### ISSUE TITLE
TODO (Сделать до 17.10)

### ISSUE THREAD

**Issue by Barkosss** [Barkosss/Permanager#38]
- [ ] Определиться с Библиотекой
- [ ] Подключить Интеграцию с Телеграммом
- [ ] Реализовать методы в InputTerminal
- [ ] Реализовать методы в OutputTerminal

**Comment by Barkosss** [comment]
# Пример реализации вывода сообщения и в терминал, и в телеграмм (от YandexGPT)

Для реализации вывода сообщений как в терминал, так и в Telegram в одном классе, используя Java, можно использовать полиморфизм и условную логику. Вот пример кода, который демонстрирует этот подход:
```
import java.util.HashMap;
import java.util.Map;

// Интерфейс для вывода сообщений
interface OutputInterface {
    void print(String message);
}

// Класс для вывода сообщений в терминал
class TerminalOutput implements OutputInterface {
    @Override
    public void print(String message) {
        System.out.println(message);
    }
}

// Класс для вывода сообщений в Telegram
class TelegramOutput implements OutputInterface {
    @Override
    public void print(String message) {
        // Здесь можно реализовать логику для отправки сообщения в Telegram
        System.out.println("Sending message to Telegram: " + message);
    }
}

// Класс, который будет использовать интерфейс для вывода сообщений
class MyClass {
    private OutputInterface output;

    public MyClass(OutputInterface output) {
        this.output = output;
    }

    public void printMessage(String message) {
        output.print(message);
    }
}

public class Main {
    public static void main(String[] args) {
        // Создание объекта для вывода в терминал
        OutputInterface terminalOutput = new TerminalOutput();

        // Создание объекта для вывода в Telegram
        OutputInterface telegramOutput = new TelegramOutput();

        // Создание объекта MyClass, который будет использовать нужный вывод в зависимости от платформы
        MyClass myClass = new MyClass(terminalOutput);
        myClass.printMessage("Hello, World!"); // Вывод в терминал

        // Переключение на вывод в Telegram
        myClass.printMessage("Hello, Telegram!"); // Вывод в Telegram
    }
}
```

В этом примере:
   1. Мы создаем интерфейс OutputInterface с методом print, который будет использоваться для вывода сообщений.
   2. Создаем два класса, реализующих интерфейс: TerminalOutput для вывода в терминал и TelegramOutput для вывода в Telegram.
   3. Класс MyClass принимает OutputInterface и использует его для вывода сообщений.
   4. В main мы создаем объекты для вывода в терминал и Telegram, а затем используем их в MyClass.

Этот подход позволяет гибко переключаться между выводом в терминал и Telegram в зависимости от контекста использования.

**Comment by Barkosss** [comment]
# Пример реализации диалога бота с пользователем (от YandexGPT)

Для реализации диалога, когда команда и чтение с Telegram находятся в разных классах, можно использовать паттерн проектирования “Шаблонный метод”. Этот паттерн позволяет определить общую структуру алгоритма в абстрактном классе, а затем переопределить некоторые шаги в конкретных подклассах.
Вот пример реализации диалога бота с пользователем, когда команда и чтение с Telegram находятся в разных классах:

**Интерфейс для обработки команд:**
```
import com.pengrad.telegrambot.model.Message;

public interface CommandHandler {
    void handleCommand(Message message);
}
Абстрактный класс для обработки обновлений:
import com.pengrad.telegrambot.TelegramBot;
import com.pengrad.telegrambot.model.Update;
import com.pengrad.telegrambot.model.UpdateListener;

public abstract class UpdateHandler implements UpdateListener {
    protected TelegramBot bot;

    public UpdateHandler(TelegramBot bot) {
        this.bot = bot;
        bot.setUpdatesListener(this);
    }

    @Override
    public void onUpdateReceived(Update update) {
        if (update.getMessage() != null) {
            Message message = update.getMessage();
            handleMessage(message);
        }
    }

    protected abstract void handleMessage(Message message);
}
```

**Класс для обработки команды `/start`:**
```
import com.pengrad.telegrambot.model.Message;

public class StartCommandHandler implements CommandHandler {
    @Override
    public void handleCommand(Message message) {
        bot.sendMessage(message.getChatId(), "Привет! Как я могу помочь тебе сегодня?");
    }
}
```

**Comment by Barkosss** [comment]
Еуыте
